
PACKET_ELTAKO_FFG7B_CLOSE = """
    gANjZW5vY2Vhbi5wcm90b2NvbC5wYWNrZXQKUmFkaW9QYWNrZXQKcQApgXEBfXECKFgLAAAAcGFj
    a2V0X3R5cGVxA0sBWAQAAAByb3JncQRL9lgJAAAAcm9yZ19mdW5jcQVOWAkAAAByb3JnX3R5cGVx
    Bk5YEQAAAHJvcmdfbWFudWZhY3R1cmVycQdOWAgAAAByZWNlaXZlZHEIY2RhdGV0aW1lCmRhdGV0
    aW1lCnEJQwoH5AMIEBMJB9fmcQqFcQtScQxYBAAAAGRhdGFxDV1xDihL9kvwSwVLh0uFS0pLIGVY
    CAAAAG9wdGlvbmFscQ9dcRAoSwBL/0v/S/9L/0tKSwBlWAYAAABzdGF0dXNxEUsgWAYAAABwYXJz
    ZWRxEmNjb2xsZWN0aW9ucwpPcmRlcmVkRGljdApxEylScRRYDgAAAHJlcGVhdGVyX2NvdW50cRVL
    AFgIAAAAX3Byb2ZpbGVxFk5YCwAAAGRlc3RpbmF0aW9ucRddcRgoS/9L/0v/S/9lWAMAAABkQm1x
    GUq2////WAYAAABzZW5kZXJxGl1xGyhLBUuHS4VLSmVYBQAAAGxlYXJucRyIdWIu
"""
PACKET_ELTAKO_FFG7B_TILTED = """
    gANjZW5vY2Vhbi5wcm90b2NvbC5wYWNrZXQKUmFkaW9QYWNrZXQKcQApgXEBfXECKFgLAAAAcGFj
    a2V0X3R5cGVxA0sBWAQAAAByb3JncQRL9lgJAAAAcm9yZ19mdW5jcQVOWAkAAAByb3JnX3R5cGVx
    Bk5YEQAAAHJvcmdfbWFudWZhY3R1cmVycQdOWAgAAAByZWNlaXZlZHEIY2RhdGV0aW1lCmRhdGV0
    aW1lCnEJQwoH5AMIFBQSAtgpcQqFcQtScQxYBAAAAGRhdGFxDV1xDihL9kvQSwVLh0uFS0pLIGVY
    CAAAAG9wdGlvbmFscQ9dcRAoSwBL/0v/S/9L/0s6SwBlWAYAAABzdGF0dXNxEUsgWAYAAABwYXJz
    ZWRxEmNjb2xsZWN0aW9ucwpPcmRlcmVkRGljdApxEylScRRYDgAAAHJlcGVhdGVyX2NvdW50cRVL
    AFgIAAAAX3Byb2ZpbGVxFk5YCwAAAGRlc3RpbmF0aW9ucRddcRgoS/9L/0v/S/9lWAMAAABkQm1x
    GUrG////WAYAAABzZW5kZXJxGl1xGyhLBUuHS4VLSmVYBQAAAGxlYXJucRyIdWIu
"""
PACKET_ELTAKO_FFG7B_OPEN = """
    gANjZW5vY2Vhbi5wcm90b2NvbC5wYWNrZXQKUmFkaW9QYWNrZXQKcQApgXEBfXECKFgLAAAAcGFj
    a2V0X3R5cGVxA0sBWAQAAAByb3JncQRL9lgJAAAAcm9yZ19mdW5jcQVOWAkAAAByb3JnX3R5cGVx
    Bk5YEQAAAHJvcmdfbWFudWZhY3R1cmVycQdOWAgAAAByZWNlaXZlZHEIY2RhdGV0aW1lCmRhdGV0
    aW1lCnEJQwoH5AMIFBQWDkikcQqFcQtScQxYBAAAAGRhdGFxDV1xDihL9kvgSwVLh0uFS0pLIGVY
    CAAAAG9wdGlvbmFscQ9dcRAoSwBL/0v/S/9L/0tASwBlWAYAAABzdGF0dXNxEUsgWAYAAABwYXJz
    ZWRxEmNjb2xsZWN0aW9ucwpPcmRlcmVkRGljdApxEylScRRYDgAAAHJlcGVhdGVyX2NvdW50cRVL
    AFgIAAAAX3Byb2ZpbGVxFk5YCwAAAGRlc3RpbmF0aW9ucRddcRgoS/9L/0v/S/9lWAMAAABkQm1x
    GUrA////WAYAAABzZW5kZXJxGl1xGyhLBUuHS4VLSmVYBQAAAGxlYXJucRyIdWIu
"""

PACKET_NODON_SDO_2105_OPEN = """gASVSwAAAAAAAAB9lCiMC3BhY2tldF90eXBllEsBjARkYXRhlF2UKEvVSwhLBUsRS1pLjUsAZYwI
b3B0aW9uYWyUXZQoSwBL/0v/S/9L/0stSwBldS4="""

PACKET_NODON_SDO_2105_CLOSED = """gASVSwAAAAAAAAB9lCiMC3BhY2tldF90eXBllEsBjARkYXRhlF2UKEvVSwlLBUsRS1pLjUsAZYwI
b3B0aW9uYWyUXZQoSwBL/0v/S/9L/0stSwBldS4="""

PACKET_NODON_SDO_2105_UPDATE_OPEN = """gASVSwAAAAAAAAB9lCiMC3BhY2tldF90eXBllEsBjARkYXRhlF2UKEvVSwhLBUsRS1pLjUsAZYwI
b3B0aW9uYWyUXZQoSwBL/0v/S/9L/0sxSwBldS4="""

PACKET_NODON_SDO_2105_UPDATE_CLOSED = """gASVSwAAAAAAAAB9lCiMC3BhY2tldF90eXBllEsBjARkYXRhlF2UKEvVSwlLBUsRS1pLjUsAZYwI
b3B0aW9uYWyUXZQoSwBL/0v/S/9L/0swSwBldS4="""


PACKET_ELTAKO_FTKB_OPEN_1 = """gASVSwAAAAAAAAB9lCiMC3BhY2tldF90eXBllEsBjARkYXRhlF2UKEvVSwhLBUsiSxRL50sAZYwI
b3B0aW9uYWyUXZQoSwBL/0v/S/9L/0s6SwBldS4="""

PACKET_ELTAKO_FTKB_OPEN_2 = """gASVSwAAAAAAAAB9lCiMC3BhY2tldF90eXBllEsBjARkYXRhlF2UKEvVSwhLBUsiSxRL50sAZYwI
b3B0aW9uYWyUXZQoSwBL/0v/S/9L/0tMSwBldS4="""

PACKET_ELTAKO_FTKB_CLOSED_1 = """gASVSwAAAAAAAAB9lCiMC3BhY2tldF90eXBllEsBjARkYXRhlF2UKEvVSwlLBUsiSxRL50sAZYwI
b3B0aW9uYWyUXZQoSwBL/0v/S/9L/0tASwBldS4="""

PACKET_ELTAKO_FTKB_CLOSED_2 = """gASVSwAAAAAAAAB9lCiMC3BhY2tldF90eXBllEsBjARkYXRhlF2UKEvVSwlLBUsiSxRL50sAZYwI
b3B0aW9uYWyUXZQoSwBL/0v/S/9L/0tBSwBldS4="""
